name: ci-web

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Install dependencies (tolerant)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      # CRA treats warnings as errors when CI=true, so... no.
      - name: Build
        env:
          CI: "false"
        run: npm run build
